/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cTokenSol from "./CToken.sol";
export type { cTokenSol };
import type * as iUniswapSol from "./IUniswap.sol";
export type { iUniswapSol };
export type { ComptrollerInterface } from "./ComptrollerInterface";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { ComptrollerInterface__factory } from "./factories/ComptrollerInterface__factory";
export type { CErc20Interface } from "./CToken.sol/CErc20Interface";
export { CErc20Interface__factory } from "./factories/CToken.sol/CErc20Interface__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export type { IUniswapV2 } from "./IUniswap.sol/IUniswapV2";
export { IUniswapV2__factory } from "./factories/IUniswap.sol/IUniswapV2__factory";
